import language from "../../language";
import i18nConfig from "../../../i18nConfig";
import { StoreProvider } from "@/redux/StoreProvider";
import { NextIntlClientProvider } from "next-intl";
import Footer from "../section/Footer";
import Header from "../section/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutBasic(props) {
  const { children, _params } = props;
  //TODO use only proyect has multilenguage
  //const {locale} = params;
  const locale = i18nConfig.defaultLocale;
  let messages;
  try {
    messages = language[locale];
    if (messages === undefined) {
      messages = language[i18nConfig.defaultLocale];
    }
  } catch (error) { }

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider locale={locale} messages={messages}>
          <StoreProvider>
            <Header />
            <div>
              {children}
            </div>
            <Footer />
          </StoreProvider>
      </NextIntlClientProvider>
      </body>
    </html>
  );
};
